"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\gui/tile_overlays/half_tile.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\gui/tile_overlays/point_selector.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\gui/tile_overlays/rail_selector.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\gui/tile_overlays/whole_tile.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/arctic/farm.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/arctic/food_processing_plant.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/arctic/forest.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/arctic/forest_tile.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/arctic/gold_mine.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/arctic/gold_mine_building.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/arctic/paper_mill.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/arctic/printing_works.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/ground_tile.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/bank.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/coal_mine.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/coal_mine_2blend.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/coal_mine_smoke.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/factory.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/farm.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/forest.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/forest_tile.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/iron_ore_mine.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/oil_refinery.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/oil_rig.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/oil_wells.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/power_station.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/power_station_sparks.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/sawmill.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/steel_mill_2x1.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/temperate/steel_mill_2x2.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/battery_farm.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/bubbles.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/bubble_generator.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/candyfloss_forest.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/candyfloss_forest_tile.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/cola_well.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/fizzy_drinks_factory.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/plastic_fountains.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/sugar_mine.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/sugar_mine_2.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/sugar_mine_3.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/sweet_shop.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/toffee_quarry.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/toy_factory.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/toyland/toy_shop.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/tropic/bank.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/tropic/copper_ore_mine.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/tropic/copper_ore_mine_2.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/tropic/copper_ore_smoke.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/tropic/diamond_mine.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/tropic/farm.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/tropic/lumber_mill.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/tropic/water_supply.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\industries/tropic/water_tower.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports/extra_bits.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports/heliport.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports/large_airport.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports/large_airport_land.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports/large_depot.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports/large_radar.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports/small_airport.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports/small_airport_land.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports/small_depot.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports/windsock.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports_toyland/extra_bits.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports_toyland/heliport.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports_toyland/large_airport.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports_toyland/large_airport_land.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports_toyland/large_depot.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports_toyland/large_radar.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports_toyland/small_airport.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports_toyland/small_airport_land.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports_toyland/small_depot.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/airports_toyland/windsock.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges/bridge_cantilever.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges/bridge_simple.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges/bridge_slopes.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges/bridge_slopes_wood.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges/bridge_supports_cantilever.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges/bridge_supports_simple.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges/bridge_supports_suspension.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges/bridge_supports_tubular.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges/bridge_supports_wood.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges/bridge_suspension.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges/bridge_tubular.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges/bridge_wood.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges_toyland/bridge_cantilever.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges_toyland/bridge_simple.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges_toyland/bridge_slopes.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges_toyland/bridge_slopes_wood.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges_toyland/bridge_supports_cantilever.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges_toyland/bridge_supports_simple.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges_toyland/bridge_supports_suspension.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges_toyland/bridge_supports_tubular.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges_toyland/bridge_supports_wood.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges_toyland/bridge_suspension.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges_toyland/bridge_tubular.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/bridges_toyland/bridge_wood.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals/aqueduct.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals/bouy.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals/canals.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals/canal_depots.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals/docks.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals/locks.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals/rivers_arctic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals/rivers_snow.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals/rivers_snow_1-4.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals/rivers_temperate.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals/rivers_tropic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals/river_slopes.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals_toyland/aqueduct.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals_toyland/bouy.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals_toyland/canals.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals_toyland/canal_depots.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals_toyland/docks.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals_toyland/locks.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals_toyland/rivers.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/canals_toyland/river_slopes.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/maglev/maglevbits/maglev_depots.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/maglev/maglevbits/maglev_stations.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/maglev/maglevbits_toyland/maglev_depots.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/maglev/maglevbits_toyland/maglev_stations.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/maglev/maglev_arctic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/maglev/maglev_crossings.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/maglev/maglev_temperate.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/maglev/maglev_toyland.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/maglev/maglev_tropic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/maglev/maglev_tunnels.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/monorail/monorailbits/monorail_depots.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/monorail/monorailbits/monorail_stations.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/monorail/monorailbits_toyland/monorail_depots.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/monorail/monorailbits_toyland/monorail_stations.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/monorail/monorail_arctic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/monorail/monorail_crossings.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/monorail/monorail_temperate.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/monorail/monorail_toyland.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/monorail/monorail_tropic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/monorail/monorail_tunnels.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/railbits/rail_depots.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/railbits/rail_stations.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/railbits/waypoint.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/railbits_toyland/rail_depots.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/railbits_toyland/rail_stations.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/railbits_toyland/waypoint.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/rail_arctic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/rail_catenary.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/rail_crossings.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/rail_fences.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/rail_fences_toyland.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/rail_signals/electric_lr.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/rail_signals/semaphore_l.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/rail_signals/semaphore_r.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/rail_temperate.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/rail_toyland.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/rail_tropic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/rail_tunnels.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/rail/tunnel_overlays.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/roadbits/one_way.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/roadbits/road_depots.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/roadbits/road_stations.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/roadbits/road_trees.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/roadbits/road_works.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/roadbits/street_light.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/roadbits_toyland/road_depots.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/roadbits_toyland/road_stations.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/roadbits_toyland/road_trees.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/roadbits_toyland/street_light.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/road_arctic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/road_concrete.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/road_concretetoyland.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/road_temperate.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/road_toyland.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/road_tropic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/road/road_tunnels.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/tram/temp.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/tram/trambits/tram_depots.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/tram/tram_catenary.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\infrastructure/tram/tram_tracks.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/disasters/aeroplanes.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/disasters/helecopter.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/disasters/large_flying_saucer.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/disasters/small_flying_saucer.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/disasters/submarines.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/disasters/zeppelin.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/effects/explosion_large.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/effects/explosion_small.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/fences/farm_fences.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/headquarters/headquarters.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/headquarters_toyland/headquarters.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/objects/bought_land.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/objects/lighthouse.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/objects/transmitter.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/arctic/1709-1715.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/arctic/1716-1722.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/arctic/1723-1729.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/arctic/1730-1736.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/arctic/1737-1743.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/arctic/1744-1750.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/arctic/1751-1757.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/arctic/1758-1764.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1576-1582.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1583-1589.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1590-1596.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1597-1603.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1604-1610.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1611-1617.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1618-1624.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1625-1631.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1632-1638.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1639-1645.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1646-1652.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1653-1659.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1660-1666.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1667-1673.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1674-1680.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1681-1685.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1688-1694.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1695-1701.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/temperate/1702-1708.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/toyland/1947-1953.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/toyland/1954-1960.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/toyland/1961-1967.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/toyland/1968-1974.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/toyland/1975-1981.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/toyland/1982-1988.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/toyland/1989-1995.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/toyland/1996-2002.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/toyland/2003-2009.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/cactus/1912-1918.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/cactus/1919-1925.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/other/1835-1841.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/other/1842-1848.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/other/1863-1869.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/other/1870-1876.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/other/1877-1883.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/other/1933-1939.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/other/1940-1946.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/1821-1827.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/1828-1834.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/1849-1855.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/1856-1862.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/1884-1890.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/1891-1897.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/1898-1904.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/1905-1911.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/1926-1932.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/fruit_plantation.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/materials_nature_uv.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/road_tree.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\landscape/trees/tropic/palm/rubber_plantation.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_bridge_recolour.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_bridge_recolour_128.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_company_colour.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_company_colour_128.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_general.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_general_old.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_general_wip.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_industry.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_nature.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_normal.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_shadeless.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_special.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_toyland.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\materials/materials_toylandnormal.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\resources/resources_cargoes.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\templates/template_4view.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\terrain/foundations_arctic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\terrain/foundations_temperate.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\terrain/foundations_toyland.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\terrain/foundations_tropic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\terrain/special_black_tile.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\terrain/terrain_arctic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\terrain/terrain_concrete.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\terrain/terrain_concretetoyland.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\terrain/terrain_fields.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\terrain/terrain_temperate.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\terrain/terrain_toyland.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\terrain/terrain_tropic.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\textures/terrain/terrain_grasses.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\textures/terrain/terrain_shadelessgrasses.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/1566-1567.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/1568-1569.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4418-4427.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4428-4433.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4434-4437+4574.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4438-4441+4575.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4442-4445+4576.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4446-4457.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4458-4461.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4462-4465.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4466-4469.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4470.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4471-4476.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4477-4479.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4480-4484.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/arctic/4485-4492.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1421-1425.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1426-1429.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1430-1433.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1434-1437.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1440-1443.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1444-1447.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1448-1453.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1454-1455.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1456-1457.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1458-1460.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1461-1463.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1464-1466.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1467-1469.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1470-1472.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1473-1475.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1476-1478.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1479-1486.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1487-1488.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1489-1490.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1491-1494.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1495-1496.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1497-1500.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1501-1506.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1507-1512.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1513-1518.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1519-1523.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1524-1529.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1530-1535.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1536-1537.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1538-1539.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1540-1545.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1546-1551.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1552-1553.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1554-1561.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1562-1565.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/1570-1575.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/4404-4405.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/4406-4417.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/temperate/statues.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4627-4629.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4630-4632.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4633-4635.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4636-4638.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4639-4641.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4642-4644.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4645-4647.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4648-4650.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4651-4656.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4657-4659.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4660-4662.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4663-4665.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4666-4668.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4669-4671.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4672-4674.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4695-4697.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/4698.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/statues.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/wrapping_res.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/toyland/wrapping_res2.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/tropic/4588-4596+4605-4607.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/tropic/4597-4600.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/tropic/4601-4603.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/tropic/4604.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/tropic/4608-4610.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/tropic/4611-4613.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/tropic/4614-4619.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/tropic/4620-4622.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\towns/tropic/4623-4625.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/air/future_aeroplanes.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/air/real_aeroplanes.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/air/real_helecopters.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/air/toyland.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/effects/breakdown_smoke.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/effects/smoke.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/effects/sparks.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/effects/steam.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/rail/maglev_engines.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/rail/monolev_wagons.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/rail/monorail_engines.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/rail/normal_wagons.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/rail/toyland_engines.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/rail/toyland_monolev_engines.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/rail/toyland_wagons.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/rail/trains_arct+trop_diesel.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/rail/trains_dmu.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/rail/trains_electric.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/rail/trains_steam.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/rail/trains_temperate_diesel.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/road/normal_buses.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/road/normal_trucks.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/road/toyland_bus.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/road/toyland_trucks.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/water/ships.blend" -a
"C:\Program Files\Blender Foundation\Blender\blender.exe" -b "M:\zbase\zbase\vehicles/water/ships_toyland.blend" -a